[book]
authors = ["Héctor Ramón Jiménez"]
language = "en"
multilingual = false
src = "src"
title = "iced — A Cross-Platform GUI Library for Rust"

[output.html]
mathjax-support = false
git-repository-url = "https://github.com/Xiao-VoV/Iced_book_Chinese_pub/main"
edit-url-template = "https://github.com/Xiao-VoV/Iced_book_Chinese_pub.git/edit/master/{path}"

[output.html.playground]
runnable = false

[preprocessor.iced]
tag = "0.13.0"
