name: Publish
on:
  push:
    branches:
      - master
    workflow_dispatch:
jobs:
  book:
    runs-on: ubuntu-22.04
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v2
      - uses: hecrj/setup-rust-action@v2
      - name: Install `mdbook`, `mdbook-iced`, and `wasm-bindgen-cli`
        run: cargo install mdbook mdbook-iced wasm-bindgen-cli
      - name: Add `wasm32-unknown-unknown` target to Rust toolchain
        run: rustup target add wasm32-unknown-unknown
      - name: Build book
        run: mdbook build
      - name: Copy CNAME
        run: cp CNAME ./book/.
      - name: Publish book
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./book
