name: Test
on:
  push:
    branches-ignore:
      - gh-pages
  pull_request:
  workflow_dispatch:
jobs:
  book:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Install mdBook
        uses: peaceiris/actions-mdbook@v1
        with:
          mdbook-version: 'latest'
      - name: Build book
        run: mdbook build
      - name: Test book
        run: mdbook test
